version: '3.8'

services:
  service-registry:
    image: spring-naming-service
    container_name: spring-naming-service
    ports:
      - 8761:8761
  gateway-service:
    image: spring-cloud-gateway
    container_name: spring-cloud-gateway
    ports:
      - 8080:8080
  first-service:
    image: splring-boot-microservices1
    container_name: splring-boot-microservices1
  second-service:
    image: splring-boot-microservices2
    container_name: splring-boot-microservices2