-- Sequence Drop and Create
drop sequence  CHATUSERSEQUENCE;
create sequence CHATUSERSEQUENCE;
drop sequence MESSAGESEQUENCE;
create sequence MESSAGESEQUENCE;
drop sequence GROUPSEQUENCE;
create sequence GROUPSEQUENCE;


--drop and create tables
drop table CHATUSERDETAILS;
create table CHATUSERDETAILS
(
USERID NUMBER NOT NULL PRIMARY KEY,
FIRSTNAME VARCHAR2(100) NOT NULL,
LASTNAME VARCHAR2(100) NOT NULL,
MOBILENUMBER NUMBER NOT NULL,
DOB VARCHAR2(30) NOT NULL,
GENDER VARCHAR2(100) NOT NULL,
ISACTIVE VARCHAR2(2) NOT NULL,
PASSWORD VARCHAR2(100) NOT NULL,
EMAIL  VARCHAR2(100) NOT NULL,
PASSWORDRESET VARCHAR2(2) NOT NULL,
CREATEDATE VARCHAR2(30) NOT NULL,
LASTUPDATE VARCHAR2(30),
DELETEDATE VARCHAR2(30)
);

drop table MESSAGESERVICE;
create table MESSAGESERVICE
(
MESSAGEID NUMBER NOT NULL PRIMARY KEY,
SENDERID NUMBER NOT NULL,
RECEIVERID NUMBER NOT NULL,
ISREAD NUMBER NOT NULL,
REFERENCEID VARCHAR2(100),

FOREIGN KEY (SENDERID) REFERENCES CHATUSERDETAILS(USERID),
FOREIGN KEY (RECEIVERID) REFERENCES CHATUSERDETAILS(USERID)
);

drop table CONVERSATIONCONTACTSERVICE;
create table CONVERSATIONCONTACTSERVICE
(
SENDERID NUMBER NOT NULL,
RECEIVERID NUMBER NOT NULL,
FOREIGN KEY (SENDERID) REFERENCES CHATUSERDETAILS(USERID),
FOREIGN KEY (RECEIVERID) REFERENCES CHATUSERDETAILS(USERID)
);

drop table GROUPDETAILS;
create table GROUPDETAILS
(
GROUPID NUMBER NOT NULL PRIMARY KEY,
GROUPNAME VARCHAR2(100) NOT NULL,
GROUPDESCRIPTION VARCHAR2(1000),
HASGROUPPIC VARCHAR2(1000),
ISGROUPACTIVE VARCHAR2(30),
CREATEDATE VARCHAR2(100) NOT NULL,
DELETEDATE VARCHAR2(30),
CREATEDBY  NUMBER
);


drop table GROUPUSERDETAILS;
create table GROUPUSERDETAILS
(
GROUPID NUMBER NOT NULL,
USERID NUMBER NOT NULL,
ISADMIN VARCHAR2(10),
FOREIGN KEY (GROUPID) REFERENCES GROUPDETAILS(GROUPID),
FOREIGN KEY (USERID) REFERENCES CHATUSERDETAILS(USERID)

);

--Alter Tables
alter table CHATUSERDETAILS ADD hasProfilePic VARCHAR2(10) default 'N';
alter table MESSAGESERVICE add createdBy DATE DEFAULT sysdate;