FROM openjdk:18
ADD target/caseanalysismanager-authenticationservice.jar caseanalysismanager-authenticationservice.jar
EXPOSE 8761
ENTRYPOINT  ["java" , "-jar" , "caseanalysismanager-authenticationservice.jar"]